# Generated by Django 4.1.7 on 2023-04-10 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=150)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
